spring:
    application:
        name: spring-jpa-manytomany
    datasource:
        url: jdbc:mysql://localhost:3306/jfsseptjava?rewriteBatchedStatements=true
        username: root
        password: manish
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create

employeeapp:
    bootstrap:
        seed-initial-data: true
